name: "Addon: Helm Chart With Spec"

on:
  workflow_dispatch:
  
jobs:
  rafay-deploy:
    runs-on: ubuntu-latest
    name: Running the Rafay Deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Rafay Addon
        uses: ./.github/actions/rafay-deploy
        with:
          name: "helm-chart-with-spec-gh"
          project: "ml-test-project"
          namespace: "ghspace"
          version: ${{ github.run_number }}
          spec: addons/helm-chart-with-spec/addon.yaml
          api-key: ${{ secrets.RAFAY_API_KEY }}