name: "Addon: Pure YAML Autogen"

on:
  workflow_dispatch:
  
jobs:
  rafay-deploy:
    runs-on: ubuntu-latest
    name: Running the Rafay Deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Rafay Addon
        uses: ./.github/actions/rafay-deploy
        with:
          name: "pure-yaml-autogen-gh"
          project: "ml-test-project"
          namespace: "ghspace"
          version: ${{ github.run_number }}
          artifact: addons/pure-yaml-autogen/manifests
          api-key: ${{ secrets.RAFAY_API_KEY }}