name: "Addon: Helm Chart Autogen"

on:
  workflow_dispatch:
  
jobs:
  rafay-deploy:
    runs-on: ubuntu-latest
    name: Running the Rafay Deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Rafay Addon
        uses: ./.github/actions/rafay-deploy
        with:
          name: "helm-chart-autogen-gh"
          project: "ml-test-project"
          namespace: "ghspace"
          version: ${{ github.run_number }}
          artifact-path: ${{ github.workspace }}/addons/helm-chart-autogen
          rafay-api-key: ${{ secrets.RAFAY_API_KEY }}